<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($item = $block->getItem()) : ?>
    <table class="qty-table">
        <tr>
            <th><?= $block->escapeHtml(__('Ordered')); ?></th>
            <td><?= (float) $item->getQtyOrdered() ?></td>
        </tr>

        <?php if ((float)$item->getQtyInvoiced()) : ?>
            <tr>
                <th><?= $block->escapeHtml(__('Invoiced')); ?></th>
                <td><?= (float) $item->getQtyInvoiced() ?></td>
            </tr>
        <?php endif; ?>

        <?php if ((float)$item->getQtyShipped()) : ?>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped')); ?></th>
                <td><?= (float) $item->getQtyShipped() ?></td>
            </tr>
        <?php endif; ?>

        <?php if ((float)$item->getQtyRefunded()) : ?>
            <tr>
                <th><?= $block->escapeHtml(__('Refunded')); ?></th>
                <td><?= (float) $item->getQtyRefunded() ?></td>
            </tr>
        <?php endif; ?>

        <?php if ((float)$item->getQtyBackOrdered()) : ?>
            <tr>
                <th><?= $block->escapeHtml(__('BackOrdered')); ?></th>
                <td><?= (float) $item->getQtyBackOrdered() ?></td>
            </tr>
        <?php endif; ?>

            <tr>
                <?php
                foreach($block->getStockQty() as $d){
                    ?>
                    <!-- <th><?= __('Inventory'); ?></th> -->
                    <td><?= $d[0] . ": "; ?> </td>
                    <td><?= $d[1]; ?> </td>
                    <?php
                }
                ?>

            </tr>
    </table>
<?php endif; ?>
